### ISSUE TITLE
[EDIT] I1.1 example's LaTeX imaginary unit is inconsistent

### ISSUE THREAD

**Issue by rootEnginear** [XanaduAI/Xanadu-Quantum-Codebook#12]
### Node number

Node I.1, Exercise I.1.1

### Current content

The imaginary part of |0> is using "i" as a symbol for an imaginary unit. But in |1>, it is a "j".

![equation](https://math.vercel.app/?color=black&from=\vert\psi\rangle=(0.87287156%2b0.43643578i)\vert0\rangle%2b(-0.13093073%2b0.17457431j)\vert1\rangle)

### Expected content

Both |0> and |1> should use "i" to avoid confusion.

![equation](https://math.vercel.app/?color=black&from=\vert\psi\rangle=(0.87287156%2b0.43643578i)\vert0\rangle%2b(-0.13093073%2b0.17457431i)\vert1\rangle)

### 

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by glassnotes** [comment]
@rootEnginear good catch, thank you! I've made the correction on our end, and it will be pushed to the live site in our next round of content updates :slightly_smiling_face:
