### ISSUE TITLE
[BUG] Cant accept terms

### ISSUE THREAD

**Issue by 00alia00** [XanaduAI/Xanadu-Quantum-Codebook#14]
### Node number

T

### Expected behavior

I scroll to the bottom, and then the accept terms button becomes active

### Actual behavior

Accept terms never becomes active

### Additional information

Tried with and without Ublock Origin enabled (Chrome/Windows)

### 

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by bopardikarsoham** [comment]
Yes @00alia00 I am facing the same issue

**Comment by bopardikarsoham** [comment]
![XanaduBug](https://user-images.githubusercontent.com/77266161/142146141-60e2adb2-a74f-4f4a-82f0-b4c9347d6049.jpg)

The Agree button does not work
