### ISSUE TITLE
[BUG] Finishing node backward will mark succeeding node incomplete

### ISSUE THREAD

**Issue by rootEnginear** [XanaduAI/Xanadu-Quantum-Codebook#16]
### Node number

Node I

### Expected behavior

When finishing lessons in Node A before Node I, Node A should still be marked as complete.

### Actual behavior

Node A will get back to an incomplete state (white circle) when it was finishing before Node I.

### Additional information

I finished Node A before Node I. Node I is marked as complete (green circle). However, Node A (which previously finished) is not anymore.

I am not certain about other node (like if you do the lesson backward, etc.). You might have to check them as well.

### 

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by glassnotes** [comment]
Thank you @rootEnginear , we will look into this as soon as possible!

**Comment by 00alia00** [comment]
Looks like its working now? (I didnt even have to scroll down)

**Comment by rootEnginear** [comment]
It's working now. Thank you 👍

**Comment by glassnotes** [comment]
I was indeed able to reproduce this, though after refreshing the page, the "A" node turned green again. We will check this out on our end nevertheless :slightly_smiling_face:
