### ISSUE TITLE
[EDIT] Add syntax of the required gate

### ISSUE THREAD

**Issue by ankit27kh** [XanaduAI/Xanadu-Quantum-Codebook#19]
### Node number

Codercise I.13.4. 

### Current content

The question does not contain the actual syntax of the MultiControlledX gate.

### Expected content

A tip/hint drop down which contains:
```
qml.MultiControlledX(control_wires=[control_1, control_2], wires=target_wire, control_values=string_of_control_values)
```

### 

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by ankit27kh** [comment]
The gate is linked, which will open the PennyLane documentation. But, it should still be directly available under the question itself.

**Comment by glassnotes** [comment]
Great idea, thanks @ankit27kh ! I'm making the update locally, and this will be included in the next content update.
