### ISSUE TITLE
Minor typo in codebook text, node I.6

### ISSUE THREAD

**Issue by andre-juan** [XanaduAI/Xanadu-Quantum-Codebook#21]
### Node number

I.6

### Current content

In the "Textbook" pannel, in the solution of Exercise I.6.3:

In the second example, $RX (\theta) \left | 0 \right \rangle$, there's a "+" sign missing in the result.

(This is a quite simple typo, but since this is the first issue I've ever opened, I thought it was better to make it simple, hehe)

### Expected content

In the last line of the result, it should be:

$ -i \sin \left ( \frac{\theta}{2} \right ) \left | 0 \right \rangle + \cos \left ( \frac{\theta}{2} \right ) \left | 1 \right \rangle $

### 

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by glassnotes** [comment]
@andre-juan thank you for catching that! This will be corrected in the next content update :slightly_smiling_face:
