### ISSUE TITLE
[EDIT] Minor typo in codebook text, node G.4

### ISSUE THREAD

**Issue by andre-juan** [XanaduAI/Xanadu-Quantum-Codebook#22]
### Node number

Node G.4, Exercise Exercise G.4.1

### Current content

In the solution of Exercise G.4.1, item (a):

The first term in the equation read $\left ( U \left | u\right \rangle \right )^\dagger \left | v\right \rangle$, but there's a $U$ missing, acting on $\left | v\right \rangle$

### Expected content

The first term in the equation should be:

$\left ( U \left | u\right \rangle \right )^\dagger U \left | v\right \rangle$

Or even

$\left ( U \left | u\right \rangle \right )^\dagger \left ( U \left | v\right \rangle \right )$

### 

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by alvaro-at-xanadu** [comment]
Thank you for letting us know! You're completely correct! We'll fix this soon.

**Comment by andre-juan** [comment]
I'm glad to help! :)
