### ISSUE TITLE
[EDIT] Minor typo in codebook text, node H.3

### ISSUE THREAD

**Issue by andre-juan** [XanaduAI/Xanadu-Quantum-Codebook#23]
### Node number

node H.3, Codercise H.3.1 (d)

### Current content

In the sentence that starts with "Hitting the submit button will plot [...]", there's an equation for the time evolution of the quantum state: $\left | \psi(t) \right \rangle = e^{e^{i \alpha t Z}} \left | 0 \right \rangle$. Notice that the exponentiation was written twice.

### Expected content

Just remove the first exponentiation: $\left | \psi(t) \right \rangle = e^{i \alpha t Z} \left | 0 \right \rangle$.

### 

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by alvaro-at-xanadu** [comment]
Yes, completely correct again! Thank you for paying such close attention!
