### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Boniface316** [XanaduAI/Xanadu-Quantum-Codebook#24]
### Node number

I.7.3

### Expected behavior

Not to accept my answer

### Actual behavior

My answer HTHT was accepted. 

### Source code

```shell
dev = qml.device("default.qubit", wires=1)

@qml.qnode(dev)
def unitary_with_h_and_t():
    
    qml.Hadamard(wires = 0)
    qml.T(wires = 0)
    qml.Hadamard(wires = 0)
    qml.T(wires = 0)
    
    

    return qml.state()
```

### 

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by alvaro-at-xanadu** [comment]
Thank you, good catch. We have some tests to fix!

**Comment by Boniface316** [comment]
It was a total accident!
