### ISSUE TITLE
[EDIT] Minor Typo in codebook text, node H.2

### ISSUE THREAD

**Issue by Sinestro38** [XanaduAI/Xanadu-Quantum-Codebook#27]
### Node number

Node H.2, exercise H.2.3(a)

### Current content

![image](https://user-images.githubusercontent.com/70229100/144718318-02cab39a-dc63-4f48-84d8-f457fecf299e.png)

**Underlined portion should be |x'> and not |x>**

### Expected content

Just switch |x> to |x'>.

### 

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by glassnotes** [comment]
Thank you @Sinestro38 , great catch, we will get that updated!
