### ISSUE TITLE
[EDIT] I1.10 Incorrect analytical expectation value

### ISSUE THREAD

**Issue by paullin03** [XanaduAI/Xanadu-Quantum-Codebook#28]
### Feature details

Solution to Exercise I.10.2.c is given as 3.022769, but using [Wolfram Alpha](https://www.wolframalpha.com/input/?i2d=true&i=%7BDivide%5B4%2C5%5D%2C-3Divide%5BPower%5Be%2C-i+*+Divide%5Bpi%2C3%5D++%5D%2C5%5D%7D%7B%7B1%2C-2i%7D%2C%7B2i%2C2%7D%7D%7BDivide%5B4%2C5%5D%2C-3Divide%5BPower%5Be%2Ci+*+Divide%5Bpi%2C3%5D++%5D%2C5%5D%7D) to calculate the provided matrix multiplication suggests that the answer should be -0.302769 instead.

Using Pennylane to measure
```
dev = qml.device("default.qubit", wires=1)
    @qml.qnode(dev)
    def qf():
        qml.MottonenStatePreparation([4 / 5, -3 / 5 * np.e ** (1j * np.pi / 3)], 0)
        return qml.expval(qml.Hermitian(np.array([[1, -2 * 1j], [2 * 1j, 2]]), 0))
print(qf())
```
also yields -0.3027687752661218

**Comment by glassnotes** [comment]
Great catch @paullin03, you are absolutely correct! We'll get this fixed in the next update.

**Comment by glassnotes** [comment]
Closing as has been updated in the live site.
