### ISSUE TITLE
Bug in Codercise I.1.2

### ISSUE THREAD

**Issue by Varary73** [XanaduAI/Xanadu-Quantum-Codebook#30]
### Feature details

Even though the output is correct, the grader shows it as incorrect!

Screenshots showing this error are attached below:

![image](https://user-images.githubusercontent.com/40118003/152493728-521354b1-a455-4e42-b2d4-c33d8ba597e8.png)
![image](https://user-images.githubusercontent.com/40118003/152493782-92bd9dda-f4b4-4b17-b1fc-cc157601c5b6.png)

**Comment by isaacdevlugt** [comment]
Hey @Varary73! Your solution isn't technically correct. When we evaluate your code internally, we are testing on _complex_ states `state_1` and `state_2`. Although `np.inner` will work for states without any imaginary phase, it won't work in general. Make sure you conjugate the bra!

I will add an error message in this problem 😄
