### ISSUE TITLE
Incorrect Action of RY on Computational Basis States in I.6

### ISSUE THREAD

**Issue by robertmoir** [XanaduAI/Xanadu-Quantum-Codebook#32]
### Feature details

Hi there,

There is a small error in the left panel equation display of the action of $RY(\theta)$ on the computational basis states in I.6 (in the discussion after codercise I.6.3). The sign of the $\sin(\theta/2)$ terms is reversed. 

Note that the expressions for this are correct in the corresponding place in the right "textbook" panel (end of the solution to exercise I.6.3).

**Comment by alvaro-at-xanadu** [comment]
Thank you so much for catching this! We'll make sure to fix it as soon as possible!

**Comment by isaacdevlugt** [comment]
Hey @robertmoir, apologies for the delay here. Looks like this issues has been fixed!

![Screen Shot 2022-12-14 at 4 39 29 PM](https://user-images.githubusercontent.com/34751083/207720487-bf3f54ce-d374-443c-bdca-b3710a70c12f.png)
