### ISSUE TITLE
[BUG] in P4

### ISSUE THREAD

**Issue by CatalinaAlbornoz** [XanaduAI/Xanadu-Quantum-Codebook#36]
### Feature details

The bug is detailed [here](https://discuss.pennylane.ai/t/possible-bug-in-qpe-module-of-the-pennylane-codebook/1666).

After finishing P.4, the codebook shows a link to “Next lesson”, while there is no module after P.4.

**Comment by towynlin** [comment]
I just encountered this bug. In browser local storage, I can see that the graph data for the P module contains 4 nodes (p.1, p.2, p.3, p.4) but it also has edges from p.4 to p.5 and p.5 to p.6.
