### ISSUE TITLE
[Bug] Error in P1.1 grader

### ISSUE THREAD

**Issue by CatalinaAlbornoz** [XanaduAI/Xanadu-Quantum-Codebook#38]
### Feature details

As explained [here](https://discuss.pennylane.ai/t/p-1-1-where-to-apply-second-hadamard/2021), the grader is marking a wrong answer (Hadamard on wire 1) as correct while marking wrong the correct answer (Hadamard on wire 0).

**Comment by isaacdevlugt** [comment]
Fixed!

**Comment by isaacdevlugt** [comment]
This issue has been fixed!
