### ISSUE TITLE
Rendering of table I.8

### ISSUE THREAD

**Issue by kmyali** [XanaduAI/Xanadu-Quantum-Codebook#45]
### Feature details

The math symbols in the table in I.8 (https://codebook.xanadu.ai/I.8) seem to not display properly. 

![image](https://user-images.githubusercontent.com/55463275/191635842-a7f07b4f-b17c-4005-be94-fe52f3f4eb3b.png)

**Comment by isaacdevlugt** [comment]
Hey @kmyali! Looks like we addressed this, but forgot to notify you and close the issue. Closing now.

![Screen Shot 2022-12-14 at 4 35 47 PM](https://user-images.githubusercontent.com/34751083/207719860-cb16bc09-54d7-4d8e-b440-a6297215b43a.png)
