### ISSUE TITLE
Fix the output for codercise I.8.3

### ISSUE THREAD

**Issue by kmyali** [XanaduAI/Xanadu-Quantum-Codebook#48]
### Feature details

According to the conversation [here](https://discuss.pennylane.ai/t/question-about-output-of-codercise-i-8-3/2181), Codercise I.8.3's needs `expansion_strategy='device'` to properly print the underlying gates from the Mottonen State Preparation.

The fix should be:
`print(qml.draw(prepare_state, expansion_strategy='device')(v))`

**Comment by isaacdevlugt** [comment]
Thanks @kmyali! Will push a fix soon.
