### ISSUE TITLE
Codercise I.10.2: Small latex rendering fix 

### ISSUE THREAD

**Issue by kmyali** [XanaduAI/Xanadu-Quantum-Codebook#50]
### Feature details

There is an equation that is not rendering properly:
![image](https://user-images.githubusercontent.com/55463275/207495006-7f9eebdd-2b6d-424f-8983-50688dd0c11b.png)

It seems that all it needs is an escape:
`num_shots` -> `num\_shots`

**Comment by isaacdevlugt** [comment]
Thanks @kmyali! Will push a fix soon.
