### ISSUE TITLE
[BUG] in codercise I.1.1

### ISSUE THREAD

**Issue by diemilio** [XanaduAI/Xanadu-Quantum-Codebook#52]
### Node number

Node I.1, codercises I.1.1

### Expected behavior

Codercise I.1.1 should throw an error if user normalizes state without taking the norm of the complex amplitudes.

Possible solution: Have grader use complex-valued variables to check answers.

### Actual behavior

Grader passes even if normalization constant is not calculated correctly (`a^2 + b^2 = 1` instead of `|a'|^2 + |b'|^2` = 1`).

### Additional information

For example, the grader passes if user inputs:

``` python3
    # CREATE A VECTOR [a', b'] BASED ON alpha AND beta SUCH THAT |a'|^2 + |b'|^2 = 1
    norm_psi = np.array([alpha,beta])/np.sqrt(alpha**2+beta**2)
    # RETURN A VECTOR
    return norm_psi
```

or 

``` python3
    # CREATE A VECTOR [a', b'] BASED ON alpha AND beta SUCH THAT |a'|^2 + |b'|^2 = 1
    psi = np.array([alpha,beta])
    norm_psi = psi/np.sqrt(np.dot(psi,psi))
    # RETURN A VECTOR
    return norm_psi
```

The correct implementations should be:

``` python3
    # CREATE A VECTOR [a', b'] BASED ON alpha AND beta SUCH THAT |a'|^2 + |b'|^2 = 1
    norm_psi = np.array([alpha,beta])/np.sqrt(abs(alpha)**2+abs(beta)**2)
    # RETURN A VECTOR
    return norm_psi
```

or 

``` python3
    # CREATE A VECTOR [a', b'] BASED ON alpha AND beta SUCH THAT |a'|^2 + |b'|^2 = 1
    psi = np.array([alpha,beta])
    norm_psi = psi/np.sqrt(np.dot(psi,psi))
    # RETURN A VECTOR
    return norm_psi
```

### Check other issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by isaacdevlugt** [comment]
Thank you for exposing this! Our behind-the-scenes test cases are letting incorrect answers pass. Will push a fix shortly
