### ISSUE TITLE
[BUG] in codercise I.1.2

### ISSUE THREAD

**Issue by diemilio** [XanaduAI/Xanadu-Quantum-Codebook#53]
### Node number

Node I.1, codercises I.1.2

### Expected behavior

Codercise I.1.2 should throw an error if user mistakenly submits the inner product `<state_2 | state_1>` instead of `<state_1 | state_2>`.

Possible solution: Have grader use complex-valued states for which `<state_1 | state_2> != <state_1 | state_1>`

### Actual behavior

Grader passes even if user submits answer for `<state_2 | state_1>`.

### Additional information

For example, the grader passes if user inputs:

```python3
    ##################
    # YOUR CODE HERE #
    ##################

    # COMPUTE AND RETURN THE INNER PRODUCT

    return  np.vdot(state_2,state_1)
```

or 

```python3
    ##################
    # YOUR CODE HERE #
    ##################

    # COMPUTE AND RETURN THE INNER PRODUCT

    return  np.dot(state_1,np.conjugate(state_2))
```

### Check other issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by isaacdevlugt** [comment]
Thank you for exposing this! Our behind-the-scenes test cases are letting incorrect answers pass. Will push a fix shortly
