### ISSUE TITLE
[BUG] New error correction nodes are not displayed

### ISSUE THREAD

**Issue by 12mB7693** [XanaduAI/Xanadu-Quantum-Codebook#58]
### Node number

Node E.1 - E.3

### Expected behavior

In the browser where I started the codebook before the new nodes on error correction were published I am expecting to see the nodes E.1 - E.3.

### Actual behavior

I cannot see the the updated content. The nodes on error correction are not displayed.

### Additional information

I am using the browser Firefox. When I am opening the codebook in a new private window, I can see the nodes E.1 - E.3.

### Check other issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by 12mB7693** [comment]
Hi @isaacdevlugt, it does not work if I reload the page. It works if I open the codebook in private mode. However, I cannot store my progress if I do it that way.

**Comment by isaacdevlugt** [comment]
Can you try clearing out your cache? NB — don't clear your cookies and site data because that will destroy your progress 😄 
![Screenshot 2023-11-30 at 12 15 29 PM](https://github.com/XanaduAI/Xanadu-Quantum-Codebook/assets/34751083/a7a64198-b06f-4f90-a705-13fa7d71fa23)

**Comment by 12mB7693** [comment]
Thank you for the suggestion. I just cleared the cache, but unfortunately it still does not work.

**Comment by 12mB7693** [comment]
It seems so that the addition of the new node about noisy quantum theory has fixed the issue, I can see all nodes now.
