### ISSUE TITLE
[BUG] Evaluation of the codercise E.1.1 takes too long (Network error)

### ISSUE THREAD

**Issue by 12mB7693** [XanaduAI/Xanadu-Quantum-Codebook#59]
### Node number

Codercise E.1.1

### Expected behavior

The code of the codercise is evaluated within a reasonable time frame.

### Actual behavior

After clicking the "Submit" button, the evaluation of the code takes more than 30 seconds and I am getting a "Network error" after a while.

### Additional information

If I am not implementing the codercise and just return "0", it still takes more than 20 seconds to display that the answer is incorrect.

### Check other issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by isaacdevlugt** [comment]
Hey @12mB7693, looks like a similar issue to what you brought up in https://github.com/XanaduAI/Xanadu-Quantum-Codebook/issues/58. Usually this can be circumvented with a hard refresh or using incognito mode.

**Comment by 12mB7693** [comment]
Hi @isaacdevlugt, I tried this beforehand, but unfortunately this does not help. I tried to submit solutions on different computers, at different times and dates, and every time I am getting a network error.

**Comment by isaacdevlugt** [comment]
Interesting... would you be able to share the code you're trying to submit?

**Comment by 12mB7693** [comment]
I tried to submit the code once again, and now it's working (although I did not change anything)! 
However, I do have the same issue with another node now ...
Shall I close the ticket anyway, since the original bug does not occur anymore?

**Comment by isaacdevlugt** [comment]
I think we're okay to close this ticket. Unfortunately there's nothing we know of on our end that would be causing this, so it must be due to your connection, browser, or something entirely unrelated 😅
