### ISSUE TITLE
"original circuit depth" in Codercise I.5.4.

### ISSUE THREAD

**Issue by AutumnPearce** [XanaduAI/Xanadu-Quantum-Codebook#60]
### Node number

Codercise I.5.4.

### Expected behavior

I believe the grader should mark "9" as the correct answer to "original depth"

### Actual behavior

the grader currently marks "8" as the correct answer to "original depth"

### Check other issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by isaacdevlugt** [comment]
Hey @AutumnPearce! 8 is actually the correct answer here. The first wire has 7 gates, the second wire has 8 gates, and the third wire has 7 gates. The maximum number of gates on a wire is 8, which is the depth. Hope this helps!

**Comment by ejdanderson** [comment]
This is a great example of the concept covered in the book portion of lesson I.2. However, the coding or exercise in lesson I.2 doesn't explicitly test for this concept. 

In my opinion, one of the following would make this more clear: 

-  The hint for I.5.4 should allude to the ability to shift gates to empty blocks
-  It should be tested in I.2
-  An explanation after the correct solution is provided

**Comment by isaacdevlugt** [comment]
Thanks @ejdanderson for your feedback. I've added something to the "Tip" given in that codercise. Should be up this week!
