### ISSUE TITLE
[BUG] I.11.3 refuses equivalent circuit

### ISSUE THREAD

**Issue by lionelbrits** [XanaduAI/Xanadu-Quantum-Codebook#66]
### Node number

Codercise I.11.3

### Expected behavior

|0> - X    
|0> - H - Z
gives
[ 0. +0.j 0. +0.j 0.7071+0.j -0.7071+0.j]
and should be accepted

### Actual behavior

|0> - X    
|0> - H - Z
gives
[ 0. +0.j 0. +0.j 0.7071+0.j -0.7071+0.j]
is not accepted accepted

|0> - X    
|0> - X - H
gives 
[ 0. +0.j 0. +0.j 0.7071+0.j -0.7071+0.j]
but is excepted. 

### Check other issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by CatalinaAlbornoz** [comment]
Hi @lionelbrits, thank you for making us aware of this bug! We'll make sure to fix it in the Codebook. Thanks for helping us make the Codebook better 🙌

**Comment by CatalinaAlbornoz** [comment]
The fix is up @lionelbrits !
You can now see it fixed in the [Codebook](https://pennylane.ai/codebook/03-circuits-many-qubits/01-multi-qubit-systems/).
Thanks again for flagging this. Let us know if you notice anything else!
